04MisPerris/cuentas/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
)


app_name = 'cuentas'

urlpatterns = [
    url(r'^iniciar_sesion/$', views.iniciar_sesion, name="iniciar_sesion"),
    url(r'^registro_usuario/$', views.registro_usuario, name='registro_usuario'),
    url(r'^cerrar_sesion/$', views.cerrar_sesion, name='cerrar_sesion'),
    url(r'^recuperar_pass/$', views.recuperar_pass, name='recuperar_pass'),
    url(r'^reset/password_reset', PasswordResetView.as_view(), {
        'template_name':'registration/password_reset_form.html', 
        'email_template_name':'registration/password_reset_email.html'}, name="password_reset"),
    url(r'^reset/password_reset_done', PasswordResetDoneView.as_view(), {'template_name':'registration/password_reset_done.html'}, name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(),  {'template_name':'accounts/password_reset_confirm.html'}, name="password_reset_confirm"),
    url(r'^reset/done', PasswordResetCompleteView.as_view(), {'template_name':'registration/password_reset_complete.html'}, name="password_reset_complete"),
]

04MisPerris/misperrishome/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'misperrishome'

urlpatterns = [
    path(r'', views.pantalla_inicio, name='pantalla_inicio'),
    path(r'lista_perritos/', views.lista_perritos, name='lista_perritos'),
    path(r'agregar_perrito/', views.agregar_perrito, name='agregar_perrito'),
    url(r'^(?P<id>\d+)/editar/$', views.editar_perrito, name="editar"),
    url(r'^(?P<id>\d+)/adoptar/$', views.adoptar_perrito, name="adoptar"),
    path(r'<id>/eliminar_perrito/', views.eliminar_perrito, name='eliminar_perrito'),
]

04MisPerris/sitiomisperris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('misperrishome.urls')),
    url(r'^cuentas/',include('cuentas.urls')),
    url('^', include('django.contrib.auth.urls')),


]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

04MisPerris/misperrishome/models.py
from django.db import models
from django.urls import reverse

class Estado(models.Model):
    descripcion = models.CharField(max_length=30)

    def __str__(self):
        return self.descripcion

class Perrito(models.Model):
    nombre = models.CharField(max_length=100)
    foto = models.ImageField(default='default.png', blank=True)
    raza = models.CharField(max_length=100)
    descripcion = models.TextField()
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, default=1)
    dueno = models.ForeignKey('auth.User', on_delete=models.CASCADE, default=1)


    def __str__(self):
        return self.nombre

04MisPerris/misperrishome/forms.py
from django import forms
from . import models

class AgregarPerrito(forms.ModelForm):
    class Meta:
        model = models.Perrito
        fields = ['nombre','raza','descripcion','foto']

class ModificarPerrito(forms.ModelForm):
    class Meta:
        model = models.Perrito
        fields = ['nombre','raza','descripcion','foto', 'estado', 'dueno']

04MisPerris/misperrishome/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Perrito
from django.contrib.auth.decorators import login_required
from . import forms
from django.contrib import messages
from .forms import ModificarPerrito
from django.views.generic.edit import UpdateView
from .models import Estado

def pantalla_inicio(request):
    return render(request, 'misperrishome/index.html')

def registro_perritos(request):
    return render(request, 'misperrishome/registro_perritos.html')

def lista_perritos(request):
    if request.method == 'POST':
        filtro = request.POST.get('filtro')
        perritos = Perrito.objects.filter(estado__pk=filtro)
    else:
        perritos = Perrito.objects.all().order_by('nombre')
    
    adoptado = get_object_or_404(Estado, pk=2)
    disponible = get_object_or_404(Estado, pk=3)

    return render(request, 'misperrishome/lista_perritos.html', {'perritos' : perritos, 'adoptado':adoptado, 'disponible':disponible})

@login_required(login_url="/cuentas/iniciar_sesion/")
def agregar_perrito(request):
    if request.method == 'POST':
        form = forms.AgregarPerrito(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('misperrishome:lista_perritos')
    else:
        form = forms.AgregarPerrito()
    return render(request, 'misperrishome/agregar_perrito.html', {'form':form})

@login_required(login_url="/cuentas/iniciar_sesion/")
def editar_perrito(request, id=None):
    instance = get_object_or_404(Perrito, id=id)
    form = ModificarPerrito(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect('misperrishome:lista_perritos')
    context = {
        "nombre":instance.nombre,
        "instance":instance,
        "form":form,
    }
    return render(request, 'misperrishome/editar_perrito.html', context)

@login_required(login_url="/cuentas/iniciar_sesion/")
def adoptar_perrito(request, id=None):
    estado = get_object_or_404(Estado, pk=2)
    perrito = get_object_or_404(Perrito, id=id)
    perrito.estado = estado
    perrito.dueno = request.user
    perrito.save(update_fields=["estado"])
    perrito.save(update_fields=["dueno"])
    return redirect('misperrishome:lista_perritos')


@login_required(login_url="/cuentas/iniciar_sesion/")
def eliminar_perrito(request, id=None):
    instance = get_object_or_404(Perrito, id=id)
    instance.delete()
    return redirect('misperrishome:lista_perritos')

04MisPerris/misperrishome/templates/misperrishome/agregar_perrito.html
{% extends 'misperrishome/base.html' %}

{% block content %}

    <div class="contacto row center-xs" id="Contacto">
        <div class=" contacto-texto col-xs-12 center-xs">
            <h1>AGREGAR PERRITO</h1>
            <hr>   
        </div>
        {% if user.username == 'admin' %}
            <div class="formulario col-xs-12 ">
                <form action="{% url 'misperrishome:agregar_perrito' %}" method="POST" enctype="multipart/form-data" id="formulario_registro">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="AGREGAR PERRITO" class="btn-agregar-perrito">
                </form>
            </div>
        {% else %}
            <div style="margin-bottom:250px;">
                <ul class="errorlist">
                    <li>Acceso Denegado: Debes ser administrador para Agregar Perritos.</li>
                </ul>
            </div>
            
        {% endif %}
        
    </div>
{% endblock %}

04MisPerris/misperrishome/templates/misperrishome/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>Mis Perris - Dinamico</title>
    <!-- ESTILOS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/flexboxgrid.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/superslides.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lightcase.css' %}">

</head>
<body id="Inicio">
    <div class="contenedor">
        <!-- REGISTRO Y LOGIN -->
        <div class="row center-xs pre-header">
            <div class="contenedor-login end-xs">
                {% if user.is_authenticated %}
                    <p>Bienvenido, {{ user.username }}!</p>

                    <form class='logout' action="{% url 'cuentas:cerrar_sesion' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="cerrar-sesion">Cerrar Sesión</button>
                    </form>
                {% else %}
                    <a href="{% url 'cuentas:iniciar_sesion' %}">Iniciar Sesión</a>
                    <a href="{% url 'cuentas:registro_usuario' %}">Registrarse</a>
                {% endif %}
            </div>
        </div>
        <!-- HEADER -->
        <header class="menu-default row middle-xs center-xs around-xs">
            <div class="logo col-xs-12 col-md-6">
                <a href="{% url 'misperrishome:pantalla_inicio' %}"><img src="{% static 'img/logo.png' %}"></a>
            </div>
            <nav class="menu col-xs-12 col-md-6">
                <a data-scroll href="{% url 'misperrishome:pantalla_inicio' %}">Inicio</a>
                {% if request.path == '/' %}
                    <a data-scroll href="#Quienes-somos">Qui&eacute;nes somos</a>
                    <a href="#Servicios">Servicios</a>
                    <a href="{% url 'misperrishome:lista_perritos' %}">Galeria</a>
                    <a data-scroll href="#Contacto">Cont&aacute;ctanos</a>
                {% else %}
                    <a data-scroll href="{% url 'misperrishome:pantalla_inicio' %}#Quienes-somos">Qui&eacute;nes somos</a>
                    <a data-scroll href="{% url 'misperrishome:pantalla_inicio' %}#Servicios">Servicios</a>
                    <a data-scroll href="{% url 'misperrishome:lista_perritos' %}">Galeria</a>
                    <a data-scroll href="{% url 'misperrishome:pantalla_inicio' %}#Contacto">Cont&aacute;ctanos</a>
                {% endif %}
                
            </nav>
        </header>
        <header class="header-mobile ">
            <div class="menu-cerrado">
                <div class="logo">
                    <img src="{% static 'img/logo.png' %}">
                </div>
                <nav class="abrir-menu">
                    <a href="#" id="btn-menu"><img src="{% static 'img/menu.png' %}" alt="Abrir Menu"></a>
                </nav>
            </div>
            <div class="menu-abierto">
                <nav class="menu-mobile" id="menu-mobile">
                    <a data-scroll href="#Inicio">Inicio</a>
                    {% if request.path == '/' %}
                    <a data-scroll href="#Quienes-somos">Qui&eacute;nes somos</a>
                    <a href="#Servicios">Servicios</a>
                    <a href="{% url 'misperrishome:lista_perritos' %}">Galeria</a>
                    <a data-scroll href="#Contacto">Cont&aacute;ctanos</a>
                {% else %}
                    <a data-scroll href="{% url 'misperrishome:pantalla_inicio' %}#Quienes-somos">Qui&eacute;nes somos</a>
                    <a data-scroll href="{% url 'misperrishome:pantalla_inicio' %}#Servicios">Servicios</a>
                    <a data-scroll href="{% url 'misperrishome:lista_perritos' %}">Galeria</a>
                    <a data-scroll href="{% url 'misperrishome:pantalla_inicio' %}#Contacto">Cont&aacute;ctanos</a>
                {% endif %}
                </nav>
            </div>
            
        </header>
    {% block content %}
    {% endblock %}
    
<!-- FOOTER -->
        <footer class="row">
            <div class="col-xs-12">
                <p>Desarrollo Web y Mobile</p>
            </div>
        </footer>
    </div>

<!-- SCRIPTS  -->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<script type="text/javascript" src="{% static 'js/lightcase.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.events.touch.min.js' %}"></script>
<script src="{% static 'js/drystone.js' %}"></script>
<script src="{% static 'js/menu.js' %}"></script>
<script src="{% static 'js/region-ciudad.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.animate-enhanced.min.js' %}"></script>
<script src="{% static 'js/smooth-scroll.min.js' %}"></script>
<script src="{% static 'js/scroll.js' %}"></script>
<script src="{% static 'js/jquery.superslides.js' %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static 'js/formulario.js' %}"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('a[data-rel^=lightcase]').lightcase({
            swipe: true
        });

        $('.grid').drystone({
            onComplete: function() {}
        });
        
        $('#menu-mobile').hide();
        
    });

    $('#slides').superslides({
        animation: 'fade',
        play: 5000,
        pagination: false,
        inherit_height_from: '.caja-slider'
    });
</script>

</body>
</html>

04MisPerris/misperrishome/templates/misperrishome/editar_perrito.html
{% extends 'misperrishome/base.html' %}

{% block content %}
<div class="contacto row center-xs" id="Contacto">
    <div class=" contacto-texto col-xs-12 center-xs">
        <h1>MODIFICAR PERRITO</h1>
        <hr>   
    </div>
    {% if user.username == 'admin' %}
        <div class="formulario col-xs-12 ">
            <form action="" method="POST" enctype="multipart/form-data" id="formulario_registro">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="MODIFICAR PERRITO" class="btn-agregar-perrito">
            </form>
        </div>
    {% else %}
        <div style="margin-bottom:250px;">
            <ul class="errorlist">
                <li>Acceso Denegado: Debes ser administrador para Agregar Perritos.</li>
            </ul>
        </div>
        
    {% endif %}
</div>
{% endblock %}

04MisPerris/misperrishome/templates/misperrishome/index.html
{% extends 'misperrishome/base.html' %}
{% load staticfiles %}
{% block content %}

    <!-- SLIDER -->
    <div class="caja-slider row center-xs">
        <div id="slides">
            <ul class="slides-container">
                <li>
                    <img src="{% static 'img/adoptados/Apolo.jpg' %}" alt="Apolo">
                    <div class="container">
                        <h1>Apolo</h1>    
                        <p>"Ahora es un nuevo miembro de la familia y nos entrega alegría día tras día."</p> 
                    </div>
                </li>
                <li>
                    <img src="{% static 'img/adoptados/Duque.jpg' %}" alt="Duque">
                    <div class="container">
                        <h1>Duque</h1>
                        <p>"Mis hijos están felices con su llegada y juegan todo el día."</p>
                    </div>
                </li>
                <li>
                    <img src="{% static 'img/adoptados/Tom.jpg' %}" alt="Tom">
                    <div class="container">
                        <h1>Tom</h1>
                        <p>"No deja de sorprendernos con su ternura y otorga alegría a nuestra familia. ¡Estamos muy felices!."</p>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    

    <div class="contenedor-social row center-xs middle-md">
        <div class="col-xs-12 col-md-4">
            <div class="fono">
                <p>+56998765431</p>
            </div>
        </div>
        <div class="col-xs-12 col-md-4">
            <div class="mensaje">
                <p>Rescate y adopci&oacute;n de perros callejeros</p>
            </div>
        </div>
        <div class="col-xs-12 col-md-4">
            <div class="redes-sociales">
                <a href="http://www.facebook.com"><img src="{% static 'img/facebook.png' %}" alt="facebook"></a> 
                <a href="https://plus.google.com/?hl=es"><img src="{% static 'img/google-plus.png' %}" alt="google"></a> 
                <a href="https://www.instagram.com/?hl=es-la"><img src="{% static 'img/instagram.png' %}" alt="instagram"></a> 
                <a href="mailto:contacto@misperris.cl"><img src="{% static 'img/mail.png' %}" alt="mail"></a>
            </div>
        </div>
    </div>

    <!-- CONTENIDO DE LA PAGINA -->
    <div class="contenedor-cuerpo row center-xs" id="Quienes-somos">
        <div class="izquierda col-xs-12 col-sm-6 end-sm">
            <h1>RESCATE</h1>
            <h3>ETAPA UNO</h3>
            <hr>

            <p>Rescatamos perros en situaci&oacute;n de peligro y/o abandono. Los rehabilitamos y los preparamos para buscarles un hogar.</p>

            <img src="{% static 'img/rescate.jpg' %}">   

        </div>

        <div class="derecha col-xs-12 col-sm-6 start-sm">
            <div class="row">
                <div class="col-xs-12 last-xs first-sm">
                        <img src="{% static 'img/crowfunding.jpg' %}">
                </div>
                <div class="col-xs-12" >
                    <h1>CROWDFUNDING</h1>
                    <h3>FINANCIAMIENTO</h3>
                    <hr>
                    <p>Sigue nuestras redes sociales para informarte acerca de las diversas campa&ntilde;as y actividades
                    que realizamos para obtener financiamiento para seguir ayudando.
                    </p>
                </div>
                
            </div>
            <div class="row center-xs start-sm">
                    <a class="btn-campanas" href="#">CAMPA&Ntilde;AS</a>
            </div>
        </div>
    </div>

    <!-- GALERIA DE IMAGENES -->
    <div class="galeria row center-xs" id="Servicios">
        <div class="galeria-texto col-xs-12 center-xs">
                <h1>RESCATADOS</h1>
                <p>Conoce a nuestros perritos rescatados. ¡Tu puedes ser su nuevo amigo!</p>
        </div>

        <div class="col-xs-12 col-md-9">
            <div class="grid">
                <a class="grid-item" href="{% static 'img/rescatados/Bigotes.jpg' %}" data-rel="lightcase:myCollection" title="Bigotes" style="text-decoration: none;">
                    <img src="{% static 'img/rescatados/Bigotes.jpg' %}" alt="Muy amoroso y jugueton.">
                </a>
                <a class="grid-item" href="{% static 'img/rescatados/Pexel.jpg' %}" data-rel="lightcase:myCollection" title="Pexel" style="text-decoration: none;">
                    <img src="{% static 'img/rescatados/Pexel.jpg' %}" alt="A Pexel le enanta jugar con niños.">
                </a>
                <a class="grid-item" href="{% static 'img/rescatados/Chocolate.jpg' %}" data-rel="lightcase:myCollection" title="Chocolate" style="text-decoration: none;">
                    <img src="{% static 'img/rescatados/Chocolate.jpg' %}" alt="Chocolate es regalón y le encanta dormir.">
                </a>
                <a class="grid-item" href="{% static 'img/rescatados/Luna.jpg' %}" data-rel="lightcase:myCollection" title="Luna" style="text-decoration: none;">
                    <img src="{% static 'img/rescatados/Luna.jpg' %}" alt="Luna es un ternura que te seguirá a todas partes.">
                </a>
                <a class="grid-item" href="{% static 'img/rescatados/Oso.jpg' %}" data-rel="lightcase:myCollection" title="Oso" style="text-decoration: none;">
                    <img src="{% static 'img/rescatados/Oso.jpg' %}" alt="Oso es un gran amigo y se adapta facilmente.">
                </a>
                <a class="grid-item" href="{% static 'img/rescatados/Maya.jpg' %}" data-rel="lightcase:myCollection" title="Maya" style="text-decoration: none;">
                    <img src="{% static 'img/rescatados/Maya.jpg' %}" alt="A Maya le encanta jugar con otros perritos.">
                </a>
                <a class="grid-item" href="{% static 'img/rescatados/Wifi.jpg' %}" data-rel="lightcase:myCollection" title="Wifi" style="text-decoration: none;">
                    <img src="{% static 'img/rescatados/Wifi.jpg' %}" alt="¿Te gusta ver películas? ¡Wifi te acompañará en todas!.">
                </a>
            </div>
        </div>
    </div>

    <!-- CONTACTO -->
    <div class="contacto row center-xs" id="Contacto">
        <div class=" contacto-texto col-xs-12 center-xs">
            <h1>CONTACTANOS</h1>
            <hr>
            <p>Si necesitas hablar con nosotros no dudes en contactarnos llenando el formulario de abajo.</p>        
        </div>
        <div class="formulario col-xs-12 ">
            <form action="index.html" method="post" id="formulario_registro">
                <div class="contenedor-campos">
                
                    <label for="nombre">Nombre Completo</label>
                    <input type="text" id="nombre" name="auxNombre" required onkeypress="return soloLetras(event);" onkeyup="this.value = this.value.toUpperCase();">

                    <label for="rut">RUT</label>  
                    <input type="text" id="rut" name="auxRut" oninput="checkRut(this)" required>    

                    <label for="fecha">Fecha de Nacimiento</label>
                    <input type="date" id="fecha" name="Fecha de Nacimiento" placeholder="Fecha de Nacimiento" max="2000-12-31" required>
                    
                    <label for="email">Email</label>
                    <input type="text" id="email" name="auxEmail" required placeholder="contacto@dominio.cl">
                    
                    <label for="fono">Teléfono de Contacto</label>
                    <input type="text" id="fono" name="auxFono" onkeypress="return SoloNumeros(event);">

                    <label for="regiones">Región</label>
                    <select name="regiones" id="regiones"></select>
                    
                    <label for="comunas">Comuna</label>
                    <select name="comunas"id="comunas"></select>

                    <label for="tipo-vivienda">Tipo de Vivienda</label>
                    <select name="tipo-vivienda" id="tipo-vivienda" required>
                        <option value="0" disabled selected>Tipo de Vivienda</option>
                        <option value="patio-grande">Casa con patio Grande</option>
                        <option value="patio-pequeño">Casa con patio pequeño</option>
                        <option value="sin-patio">Casa sin patio</option>
                        <option value="depto">Departamento</option>
                    </select>
                    <button type="submit">ENVIAR</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

04MisPerris/misperrishome/templates/misperrishome/lista_perritos.html
{% extends 'misperrishome/base.html' %}

{% block content %}
    <h1 style="text-align: center;margin:30px 0px;">Nuestros Perris</h1>
    <div class="filtro-lista">

        
        <form action="{% url 'misperrishome:lista_perritos' %}" method="POST" class="form-filtro row">
            {% csrf_token %}
            <select name="filtro" class="col-xs-6">
                <option value="0" selected disabled>Seleccione Estado</option>
                <option value="1">Rescatado</option>
                <option value="3">Disponible</option>
                <option value="2">Adoptado</option>
                
            </select>
            <input type="submit" value="Filtrar" class="col-xs-6">
        </form>

        
        {% if user.username == 'admin' %}
            <a href="{% url 'misperrishome:agregar_perrito' %}" class="btn-agregar ">Agregar Perrito</a>
        {% endif %}
        
    </div>
    
    <div class="perritos">
        {% for perrito in perritos %}
        <div class="perrito-item row">
            <div class="col-xs-3 col-imagen">
                <img src="{{ perrito.foto.url }}" alt="{{ perrito.nombre }}">
            </div>
            <div class="col-xs-9 col-datos">
                <h2>{{ perrito.nombre }}</h2>
                <p class="perrito-raza">{{ perrito.raza }}</p>
                <p>{{ perrito.descripcion }}</p><br>
                {% if user.username == 'admin' %}
                    <a href="{% url 'misperrishome:editar' id=perrito.id %}" class="btn-perrito-item">Modificar</a>
                    <a href="{% url 'misperrishome:eliminar_perrito' id=perrito.id %}" class="btn-perrito-item">Eliminar</a>
                {% else %}
                    {% if perrito.estado == adoptado %}
                        <p class="bottom-xs">Adoptado por {{ perrito.dueno }}</p>
                    {% else %}
                        {% if perrito.estado == disponible %}
                            <a href="{% url 'misperrishome:adoptar' id=perrito.id %}" class="btn-perrito-item">Adoptar</a>
                        {% else %}
                            <p>{{ perrito.estado }}</p>
                        {% endif %}
                    {% endif %}
                       
                {% endif %}
            </div>
            
            
        </div>
        {% endfor %}
    </div>
{% endblock %}

04MisPerris/misperrishome/templates/misperrishome/modificar_perrito.html
{% extends 'misperrishome/base.html' %}

{% block content %}

    <div class="contacto row center-xs" id="Contacto">
        <div class=" contacto-texto col-xs-12 center-xs">
            <h1>MODIFICAR PERRITO</h1>
            <hr>   
        </div>
        {% if user.username == 'admin' %}
            <div class="formulario col-xs-12 ">
                <form action="{% url 'misperrishome:modificar_perrito' %}" method="POST" enctype="multipart/form-data" id="formulario_registro">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="MODIFICAR PERRITO" class="btn-agregar-perrito">
                </form>
            </div>
        {% else %}
            <div style="margin-bottom:250px;">
                <ul class="errorlist">
                    <li>Acceso Denegado: Debes ser administrador para Agregar Perritos.</li>
                </ul>
            </div>
            
        {% endif %}
        
    </div>
{% endblock %}

04MisPerris/misperrishome/templates/misperrishome/perrito_detalle.html
{% extends 'misperrishome/base.html' %}

{% block content %}
    <h1>{{ perrito.nombre }}</h1>
    <img src="{{ perrito.foto.url }}" alt="{{ perrito.nombre }}">
    <p>{{ perrito.raza }}</p>
    <p>{{ perrito.descripcion }}</p>
    <p>{{ perrito.estado }}</p>

{% endblock %}