04MisPerris/cuentas/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
)


app_name = 'cuentas'

urlpatterns = [
    url(r'^iniciar_sesion/$', views.iniciar_sesion, name="iniciar_sesion"),
    url(r'^registro_usuario/$', views.registro_usuario, name='registro_usuario'),
    url(r'^cerrar_sesion/$', views.cerrar_sesion, name='cerrar_sesion'),
    url(r'^recuperar_pass/$', views.recuperar_pass, name='recuperar_pass'),
    url(r'^reset/password_reset', PasswordResetView.as_view(), {
        'template_name':'registration/password_reset_form.html', 
        'email_template_name':'registration/password_reset_email.html'}, name="password_reset"),
    url(r'^reset/password_reset_done', PasswordResetDoneView.as_view(), {'template_name':'registration/password_reset_done.html'}, name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(),  {'template_name':'accounts/password_reset_confirm.html'}, name="password_reset_confirm"),
    url(r'^reset/done', PasswordResetCompleteView.as_view(), {'template_name':'registration/password_reset_complete.html'}, name="password_reset_complete"),
]

04MisPerris/sitiomisperris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('misperrishome.urls')),
    url(r'^cuentas/',include('cuentas.urls')),
    url('^', include('django.contrib.auth.urls')),


]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

04MisPerris/cuentas/models.py
from django.db import models

# Create your models here.

04MisPerris/cuentas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Opcional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Opcional.')
    email = forms.EmailField(max_length=254, help_text='Requerido. Ingrese un correo valido.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
    
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].label = "Nombres"
        self.fields['last_name'].label = "Apellidos"

04MisPerris/cuentas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .forms import SignUpForm

# Create your views here.

def registro_usuario(request):
    if request.method == 'POST': #validamos que se haya submiteado algo
        form = SignUpForm(request.POST) # Se crea instancia del formulario con la informacion de POST
        if form.is_valid(): # validamos formulario
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('misperrishome:pantalla_inicio')
    else:
        form = SignUpForm() # Se crea instancia vacia del formulario
    return render(request, 'cuentas/registro_usuario.html', {'form':form})

def iniciar_sesion(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Se inicia sesion
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('misperrishome:pantalla_inicio')
    else:
        form = AuthenticationForm()
    return render(request, 'cuentas/iniciar_sesion.html', {'form':form})

def cerrar_sesion(request):
    if request.method == 'POST':
        logout(request)
        return redirect('misperrishome:pantalla_inicio')


def recuperar_pass(request):
    return render(request, 'cuentas/recuperar_pass.html')

04MisPerris/cuentas/templates/cuentas/iniciar_sesion.html
{% extends 'misperrishome/base.html' %}

{% block content %}
    <!-- INICIAR SESION -->
    <div class="contacto row center-xs" id="Contacto">
        <div class=" contacto-texto col-xs-12 center-xs">
            <h1>INICIAR SESION</h1>
            <hr>   
        </div>
        <div class="formulario col-xs-12 "  style="margin">
            <form action="{% url 'cuentas:iniciar_sesion' %}" method="post" id="formulario_registro">
                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <button type="submit" value="Login">INICIAR SESION</button>
                <a style="color: #000;" href="{% url 'cuentas:password_reset' %}">Recuperar contraseña</a>
            </form>
        </div>
    </div>
{% endblock %}

04MisPerris/cuentas/templates/cuentas/recuperar_pass.html
{% extends 'misperrishome/base.html' %}

{% block content %}
    <!-- INICIAR SESION -->
    <div class="contacto row center-xs" id="Contacto">
        <div class=" contacto-texto col-xs-12 center-xs">
            <h1>Recuperar Contraseña</h1>
            <hr>   
        </div>
        <div class="formulario col-xs-12 ">
            <form action="{% url 'cuentas:recuperar_pass' %}" method="post" id="formulario_registro">
                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <button type="submit" value="Login">ENVIAR CONTRASEÑA</button>
            </form>
        </div>
    </div>
{% endblock %}

04MisPerris/cuentas/templates/cuentas/registro_usuario.html
{% extends 'misperrishome/base.html' %}

{% block content %}
    <!-- REGISTRO DE USUARIO -->
    <div class="contacto row center-xs" id="Contacto">
        <div class=" contacto-texto col-xs-12 center-xs">
            <h1>REGISTRO DE USUARIO</h1>
            <hr>   
        </div>
        <div class="formulario col-xs-12 ">
            <form action="/cuentas/registro_usuario/" method="post" id="formulario_registro">
                {% csrf_token %}
                {{ form }}

                <button type="submit" value="Signup">REGISTRARSE</button>
            </form>
        </div>
    </div>
{% endblock %}